import os
import pandas as pd
from tqdm import tqdm
from sklearn.preprocessing import MinMaxScaler
from pinecone import Pinecone, ServerlessSpec
from dotenv import load_dotenv

# ----------------------------------------
# Setup
# ----------------------------------------
load_dotenv()

API_KEY = os.getenv("API_KEY")
INDEX_NAME = "f1-overtake"
MAX_BATCH = 1000

# Input CSV template (generated by FastF1 script)
OUTPUT_CSV_TEMPLATE = "overtake_laps_{}_usa.csv"
YEARS = [2022, 2023, 2024]

# -----------------------------
# Feature columns (vector)
# -----------------------------
FEATURE_COLS = [
    "LapNumber",        # numeric lap
    "Position",         # normalized position
    "Compound",         # normalized tyre type
    "TyreLife",         # normalized
    "TrackTemp",        # normalized
    "Rainfall",         # 0/1
    "DRS_Ratio",        # fraction of lap DRS active
    "Brake_Ratio",      # fraction of lap braking
    "AvgDistanceAhead", # normalized meters to car ahead
    "TrackNormalized"
]
# -----------------------------
# Metadata columns
# -----------------------------
METADATA_COLS = ["TrackName", "Year", "Driver", "Team"]

# ----------------------------------------
# Step 1: Load and Combine CSVs
# ----------------------------------------
dfs = []
for year in YEARS:
    path = OUTPUT_CSV_TEMPLATE.format(year)
    if not os.path.exists(path):
        print(f"⚠️ File not found: {path}, skipping {year}...")
        continue

    df = pd.read_csv(path)
    df["Year"] = year

    # Fill missing telemetry data with 0
    for col in FEATURE_COLS:
        if col not in df.columns:
            df[col] = 0.0

    # Normalize Compound to 0–1
    COMPOUND_MAP = {"SOFT": 1, "MEDIUM": 2, "HARD": 3, "INTERMEDIATE": 4, "WET": 5, "UNKNOWN": 0}
    df["Compound"] = df["Compound"].map(COMPOUND_MAP).fillna(0) / 5

    dfs.append(df)

if not dfs:
    raise ValueError("❌ No valid CSVs found. Check file paths.")

combined = pd.concat(dfs, ignore_index=True)
print(f"✅ Combined shape: {combined.shape}")

# ----------------------------------------
# Step 2: Normalize numeric telemetry columns
# ----------------------------------------
scaler = MinMaxScaler()
combined[FEATURE_COLS] = scaler.fit_transform(combined[FEATURE_COLS].fillna(0))

# Save combined file for debugging
combined.to_csv("overtake_all_years_combined.csv", index=False)
print("💾 Saved normalized dataset: overtake_all_years_combined.csv")

# ----------------------------------------
# Step 3: Pinecone Setup
# ----------------------------------------
pc = Pinecone(api_key=API_KEY)

if INDEX_NAME not in pc.list_indexes().names():
    print(f"🧱 Creating index '{INDEX_NAME}'...")
    pc.create_index(
        name=INDEX_NAME,
        dimension=len(FEATURE_COLS),  # now 9-dimensional vector
        metric="cosine",
        spec=ServerlessSpec(cloud="aws", region="us-east-1"),
    )

index = pc.Index(INDEX_NAME)
print(f"📡 Connected to Pinecone index: {INDEX_NAME}")

# ----------------------------------------
# Step 4: Prepare vectors, metadata, and IDs
# ----------------------------------------
vectors = combined[FEATURE_COLS].values.tolist()
metadata = combined[METADATA_COLS].to_dict(orient="records")
ids = [f"{row['Year']}_{i}" for i, row in combined.iterrows()]

print(f"\n🚀 Uploading {len(vectors)} vectors to Pinecone...\n")

# ----------------------------------------
# Step 5: Upload in batches
# ----------------------------------------
for i in tqdm(range(0, len(vectors), MAX_BATCH), desc="Uploading batches"):
    batch_vecs = vectors[i : i + MAX_BATCH]
    batch_meta = metadata[i : i + MAX_BATCH]
    batch_ids = ids[i : i + MAX_BATCH]
    index.upsert(vectors=list(zip(batch_ids, batch_vecs, batch_meta)))

print("✅ All vectors uploaded successfully!")

# ----------------------------------------
# Step 6: Index stats
# ----------------------------------------
stats = index.describe_index_stats()
print("\n📊 Pinecone Index Stats:")
print(stats)
